### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tiagocardosoweb**

### CODE REVIEW

**Comment by tiagocardosoweb** [comment]
GTA MP doesn't exist. The converter you created is for GTA:Network API, also works with GT-MP because GT-MP is a fork from GTA:N stolen code.

**Comment by Hirsw0w** [comment]
I don't know who did what so I have created 2 repositorys 1 for gta MP and for GTA Network.

**Comment by tiagocardosoweb** [comment]
Still, GTA MP != GTA:Network != GT-MP.
GTA:MP/GTA-MP was shutdown by T2.
https://gta-mp.net

**Comment by Hirsw0w** [comment]
oh I thought GT-MP its just the domain and gta mp full name lol I'll fix it for the right name

**Pull request closed without merging**
